/*
This file is part of Jedi Academy.

    Jedi Academy is free software: you can redistribute it and/or modify
    it under the terms of the GNU General Public License as published by
    the Free Software Foundation, either version 2 of the License, or
    (at your option) any later version.

    Jedi Academy is distributed in the hope that it will be useful,
    but WITHOUT ANY WARRANTY; without even the implied warranty of
    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
    GNU General Public License for more details.

    You should have received a copy of the GNU General Public License
    along with Jedi Academy.  If not, see <http://www.gnu.org/licenses/>.
*/
// Copyright 2001-2013 Raven Software

//g_items.h

#ifndef __ITEMS_H__
#define __ITEMS_H__

// Items enums
enum 
{
ITM_NONE,

ITM_SABER_PICKUP,
ITM_BLASTER_PISTOL_PICKUP,
ITM_BLASTER_PICKUP,
ITM_DISRUPTOR_PICKUP,
ITM_REPEATER_PICKUP,
ITM_FLECHETTE_PICKUP,
ITM_BOWCASTER_PICKUP,
ITM_ROCKET_LAUNCHER_PICKUP,
ITM_NOGHRI_STICK_PICKUP,
ITM_DEMP2_PICKUP,
ITM_CONCUSSION_RIFLE_PICKUP,
ITM_THERMAL_DET_PICKUP,
ITM_TRIP_MINE_PICKUP,
ITM_DET_PACK_PICKUP,
ITM_MELEE,
ITM_BOW_PICKUP,
ITM_CROSSBOW_PICKUP,
ITM_SLING_PICKUP,
ITM_THROWABLE_PICKUP,
ITM_STUN_BATON_PICKUP,
ITM_TUSKEN_STAFF_PICKUP,
ITM_TUSKEN_RIFLE_PICKUP,
ITM_CANNON_PICKUP,
ITM_HOOKER_PICKUP,
ITM_SCEPTER_PICKUP,
ITM_DARK_PICKUP,
ITM_LIGHT_PICKUP,
ITM_LIGHTNING_PICKUP,
ITM_FIRE_PICKUP,
ITM_FLAME_PICKUP,
ITM_AIR_PICKUP,
ITM_WATER_PICKUP,
ITM_EARTH_PICKUP,
ITM_SONIC_PICKUP,
ITM_PSYCHIC_PICKUP,
ITM_WOOD_PICKUP,
ITM_METAL_PICKUP,
ITM_SPIRIT_PICKUP,
ITM_POISON_PICKUP,
ITM_HOLY_PICKUP,
ITM_NECRO_PICKUP,
ITM_BRYAR_PISTOL_PICKUP,
ITM_EMPLACED_GUN_PICKUP,
ITM_ATST_MAIN_PICKUP,
ITM_ATST_SIDE_PICKUP,
ITM_TIE_FIGHTER_PICKUP,
ITM_JAWA_PICKUP,
ITM_BOT_LASER_PICKUP,
ITM_RAPID_FIRE_CONC_PICKUP, 
ITM_ANTIMATTER_PICKUP,		// Razzi ad Antimateria, Key ' 
ITM_DEFENSE_PICKUP,		// Difese dei caccia: scudi, chaff, flare etc - Roll Key ì
ITM_DRONE_PICKUP,		// Mine e contromisure dei caccia - Roll Key ì
ITM_POSITRON_PICKUP,		// Cannone ad antimateria, arma suprema. Roll Key ì 
ITM_TURRET_PICKUP,
ITM_SUMMON1_PICKUP,
ITM_SUMMON2_PICKUP,
ITM_SUMMON3_PICKUP,
ITM_SUMMON4_PICKUP,
ITM_MORPH1_PICKUP,
ITM_MORPH2_PICKUP,
ITM_MORPH3_PICKUP,
ITM_MORPH4_PICKUP,
ITM_ITEM1_PICKUP,
ITM_ITEM2_PICKUP,
ITM_ITEM3_PICKUP,
ITM_ITEM4_PICKUP,
ITM_ITEM5_PICKUP,
ITM_ITEM6_PICKUP,
ITM_ITEM7_PICKUP,
ITM_ITEM8_PICKUP,
ITM_ITEM9_PICKUP,
ITM_ITEM10_PICKUP,
ITM_ITEM11_PICKUP,
ITM_ITEM12_PICKUP,
ITM_AMMO_FORCE_PICKUP,
ITM_AMMO_BLASTER_PICKUP,
ITM_AMMO_POWERCELL_PICKUP,
ITM_AMMO_METAL_BOLTS_PICKUP,
ITM_AMMO_ROCKETS_PICKUP,
ITM_AMMO_EMPLACED_PICKUP,
ITM_AMMO_THERMAL_PICKUP,
ITM_AMMO_TRIPMINE_PICKUP,
ITM_AMMO_DETPACK_PICKUP,

ITM_FORCE_HEAL_PICKUP,
ITM_FORCE_LEVITATION_PICKUP,
ITM_FORCE_SPEED_PICKUP,
ITM_FORCE_PUSH_PICKUP,
ITM_FORCE_PULL_PICKUP,
ITM_FORCE_TELEPATHY_PICKUP,
ITM_FORCE_GRIP_PICKUP,
ITM_FORCE_LIGHTNING_PICKUP,
ITM_FORCE_SABERTHROW_PICKUP,

ITM_BATTERY_PICKUP,
ITM_SEEKER_PICKUP,
ITM_SHIELD_PICKUP,
ITM_BACTA_PICKUP,
ITM_DATAPAD_PICKUP,
ITM_BINOCULARS_PICKUP,
ITM_SENTRY_GUN_PICKUP,
ITM_LA_GOGGLES_PICKUP,

ITM_MEDPAK_PICKUP,
ITM_SHIELD_SM_PICKUP,
ITM_SHIELD_LRG_PICKUP,
ITM_GOODIE_KEY_PICKUP,
ITM_SECURITY_KEY_PICKUP,
ITM_BLOODGUN_PICKUP,
ITM_NUM_ITEMS
}; 

// Inventory item enums
enum //# item_e
{
	INV_ELECTROBINOCULARS,
	INV_BACTA_CANISTER,
	INV_SEEKER,
	INV_LIGHTAMP_GOGGLES,
	INV_SENTRY,		
	//# #eol
	INV_GOODIE_KEY,	// don't want to include keys in the icarus list
	INV_SECURITY_KEY,

	INV_MAX						// Be sure to update MAX_INVENTORY
};

#endif
